"""Generate files/cv_body.tex from the YAML sources.

Papers come from the Jekyll collections (_publications, _projects, _portuguese),
which the website also renders, so a paper is described in exactly one place.
Everything else comes from _data/cv.yml.

Usage, from anywhere:   python3 files/build_cv.py
Then:                   latexmk -pdf -cd files/Diogo_cv.tex

Requires PyYAML (pip install pyyaml).
"""
import collections
import pathlib
import re
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "files" / "cv_body.tex"

# ---------------------------------------------------------------- helpers ----

ESCAPES = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
           "_": r"\_", "{": r"\{", "}": r"\}"}


def tex(text):
    """Escape LaTeX specials in body text. Leaves '--' en-dashes intact."""
    return "".join(ESCAPES.get(c, c) for c in str(text))


def url(link):
    """Escape only what breaks inside \\href's first argument."""
    return str(link).replace("#", r"\#").replace("%", r"\%")


def shown(item):
    """Records carry include: false when retired but worth keeping on file."""
    return isinstance(item, dict) and item.get("include") is not False


def names(coauthors):
    """['A','B','C'] -> 'A, B and C'. Accepts plain strings or {name: ...}."""
    labels = [tex(c["name"] if isinstance(c, dict) else c) for c in coauthors]
    if not labels:
        return ""
    if len(labels) == 1:
        return labels[0]
    return ", ".join(labels[:-1]) + " and " + labels[-1]


def est_lines(text, chars_per_line=72):
    """Rough rendered height of text set in the 0.75\\textwidth minipages.

    Only used to size \\needspace. The minipages are atomic, so an underestimate
    strands the bold heading above them at a page break; erring high just moves
    the whole block down a little earlier.
    """
    return max(1, -(-len(text) // chars_per_line))


def load_collection(folder):
    """Read YAML front matter from every .md in a collection folder."""
    papers = []
    for path in sorted((ROOT / folder).glob("*.md")):
        match = re.match(r"^---\s*\n(.*?)\n---\s*\n?(.*)$",
                         path.read_text(encoding="utf-8"), re.S)
        data = yaml.safe_load(match.group(1)) or {}
        data["_sort"] = path.name[:2]      # numeric filename prefix
        papers.append(data)
    return papers


def paper_block(paper):
    """Title (linked), then the journal line, then coauthors.

    `journal` carries publication status for unpublished work ("Under review",
    "R&R at Journal of X"), so a single rule covers both cases: with a year it
    becomes a full citation, without one it prints on its own.
    """
    lines = []
    title = tex(paper["title"])
    if paper.get("doilink"):
        lines.append(r"\href{%s}{%s}" % (url(paper["doilink"]), title))
    else:
        lines.append(title)

    if paper.get("journal"):
        line = r"\textit{%s}" % tex(paper["journal"])
        if paper.get("year"):          # published: "Economic Theory, 82, 251--272 (2026)"
            bits = [line]
            if paper.get("volume"):
                bits.append(str(paper["volume"]))
            locator = paper.get("pages") or paper.get("issue")
            if locator:
                bits.append(tex(locator))
            line = ", ".join(bits) + " (%s)" % paper["year"]
        lines.append(line)

    if paper.get("coauthors"):
        lines.append("(with %s)" % names(paper["coauthors"]))

    # Keep the whole entry on one page: if fewer than four lines remain, break
    # first rather than orphan the title from its journal and coauthors.
    return r"\needspace{4\baselineskip}" + "\n" + " \\\\\n".join(lines)


# ------------------------------------------------------------------ build ----

cv = yaml.safe_load((ROOT / "_data" / "cv.yml").read_text(encoding="utf-8"))
out = ["%% GENERATED by files/build_cv.py -- do not edit by hand.",
       "%% Edit _data/cv.yml or the _publications/_projects/_portuguese "
       "front matter instead.", ""]

# Contact -------------------------------------------------------------------
c = cv["contact"]
email_cell = r"E-Mail: \url{%s}" % c["email"]
site_cell = r"Website: \url{%s}" % c["website"]

# Size the right column to the exact width of its widest cell, so the longest
# line (the website) ends flush with the right margin, in line with the header
# rule and the right-aligned dates below. @{} suppresses the outer \tabcolsep at
# both edges, which would otherwise inset the table by 6pt on each side; the 1pt
# is rounding guard only, far too small to see but enough to prevent a wrap.
out += [r"\section{Contact Information}", "",
        r"\settowidth{\cvcontactright}{%s}" % email_cell,
        r"\settowidth{\cvcontacttmp}{%s}" % site_cell,
        r"\ifdim\cvcontacttmp>\cvcontactright"
        r"\setlength{\cvcontactright}{\cvcontacttmp}\fi",
        r"\addtolength{\cvcontactright}{1pt}",
        r"\setlength{\cvcontactleft}{\textwidth}",
        r"\addtolength{\cvcontactleft}{-\cvcontactright}",
        r"\addtolength{\cvcontactleft}{-2\tabcolsep}",
        r"\setlength{\LTleft}{0pt}",
        r"\setlength{\LTright}{0pt}",
        r"\begin{longtable}{@{}p{\cvcontactleft}p{\cvcontactright}@{}}",
        r"%s & %s \\" % (tex(c["department"]), email_cell),
        r"%s & %s \\" % (tex(c["address"]), site_cell),
        r"%s & \\" % tex(c["city"]),
        r"\end{longtable}", ""]

# Appointments --------------------------------------------------------------
out += [r"\section{Academic Appointments}", ""]
for place in cv["appointments"]:
    out.append(r"\textbf{%s} \\" % tex(place["institution"]))
    # \\ goes *between* roles, never after the last one: a trailing \\ followed
    # by the blank line below is a line break plus a paragraph break, which
    # double-spaces the gap to the next institution.
    out.append(" \\\\\n".join(
        r"$\cdot$ %s, \emph{%s} \hfill %s" %
        (tex(role["unit"]), tex(role["title"]), tex(role["years"]))
        for role in place["roles"]))
    out.append("")

# Education -----------------------------------------------------------------
out += [r"\section{Education}", ""]
for place in cv["education"]:
    out.append(r"\textbf{%s} \\" % tex(place["institution"]))
    out.append(" \\\\\n".join(
        r"$\cdot$ %s \hfill %s" % (tex(deg["degree"]), tex(deg["years"]))
        for deg in place["degrees"]))
    out.append("")

# Research interests --------------------------------------------------------
# Split across two lines so the block is at least as tall as the two-line
# section label in the margin; otherwise the next label crowds it.
interests = [tex(i) for i in cv["research_interests"]]
half = max(1, (len(interests) + 1) // 2)
out += [r"\section{Research Interests}", "",
        ", ".join(interests[:half]) + r", \\",
        ", ".join(interests[half:]), ""]

# Published papers, most recent first ---------------------------------------
published = sorted(load_collection("_publications"),
                   key=lambda p: (p["year"], p["_sort"]), reverse=True)
out += [r"\section{Peer-Reviewed Papers}", ""]
for paper in published:
    out += [paper_block(paper), ""]

portuguese = sorted(load_collection("_portuguese"),
                    key=lambda p: (p["year"], p["_sort"]), reverse=True)
out += [r"\section{Peer-Reviewed Papers\\ (Portuguese)}", ""]
for paper in portuguese:
    out += [paper_block(paper), ""]

# Working papers: those carrying a status label first, then unlabelled drafts --
working = sorted(load_collection("_projects"),
                 key=lambda p: (0 if p.get("journal") else 1, -int(p["_sort"])))
out += [r"\section{Working \\ Papers}", ""]
for paper in working:
    out += [paper_block(paper), ""]

# Work in progress ----------------------------------------------------------
if cv.get("work_in_progress"):
    out += [r"\section{Work in Progress}", ""]
    for item in cv["work_in_progress"]:
        out.append(tex(item["title"]) + r" \\")
        out += ["(with %s)" % names(item["coauthors"]), ""]

# Selected presentations, flat and reverse-chronological --------------------
talks = [t for t in cv.get("presentations", []) if shown(t)]
talks.sort(key=lambda t: t["year"], reverse=True)
if talks:
    out += [r"\section{Selected \\ Presentations \\ "
            r"{\protect\footnotesize \emph{Invited}}}", ""]
    rendered = []
    for talk in talks:
        label = tex(talk["venue"])
        if talk.get("invited"):
            label = r"\emph{%s}" % label
        rendered.append("%s (%s)" % (label, talk["year"]))
    out += [r"\begin{minipage}[t]{0.95\textwidth}",
            r" $\cdot$ ".join(rendered), r"\end{minipage}", ""]

# Teaching ------------------------------------------------------------------
out += [r"\section{Teaching\\ Experience}", ""]
for place in cv["teaching"]:
    out.append(r"\textbf{%s} \\" % tex(place["institution"]))
    for course in place["courses"]:
        out.append(r"$\cdot$ \textit{%s, %s level} \\" %
                   (tex(course["title"]), tex(course["level"])))
    out.append("")

# Service -------------------------------------------------------------------
# Every sub-block gets the same shape: a bold label, then one continuous
# $\cdot$ run indented beneath it. The "University of South Florida" heading is
# dropped -- everything under it was USF, and refereeing is already separate --
# which removes a level of nesting and makes the whole section one pattern.
svc = cv["service"]
blocks = []
for place in svc.get("institutional", []):
    for unit in place["units"]:
        blocks.append((unit["unit"], [tex(r) for r in unit["roles"]]))
for key, label in [("scientific_committee", "Scientific Committee"),
                   ("discussant", "Discussant"),
                   ("referee", "Referee Reports")]:
    if svc.get(key):
        blocks.append((label, [tex(v) for v in svc[key]]))

out += [r"\section{Service}", ""]
for label, items in blocks:
    body = r" $\cdot$ ".join(items)
    out += [r"\needspace{%d\baselineskip}" % (est_lines(body) + 1),
            r"\textbf{%s:} \\" % tex(label),
            r"\indent \hspace{1cm} \begin{minipage}[t]{0.75\textwidth}",
            body,
            r"\end{minipage}", ""]

# Advising ------------------------------------------------------------------
adv = cv.get("advising", {})
if adv.get("chair") or adv.get("member"):
    out += [r"\section{Advising}", ""]
for key, label in [("chair", "Dissertation Chair"),
                   ("member", "Dissertation Committee")]:
    if not adv.get(key):
        continue
    students = adv[key]

    # Fold whatever every student shares into the label instead of repeating it
    # after each name. The commonest institution/degree pair becomes the
    # default; only students who differ carry a parenthetical.
    common = collections.Counter(
        (s["institution"], s["degree"]) for s in students).most_common(1)[0][0]
    qualifier = ", ".join(common)
    if any((s["institution"], s["degree"]) != common for s in students):
        qualifier += " unless noted"

    # A role shared by everyone belongs in the heading ("Dissertation Co-Chair").
    roles = {s.get("role") for s in students}
    shared_role = next(iter(roles)) if len(roles) == 1 else None
    heading = "Dissertation %s" % shared_role if shared_role else label

    entries = []
    for s in students:
        detail = []
        if not shared_role and s.get("role"):
            detail.append(s["role"])
        if (s["institution"], s["degree"]) != common:
            detail += [s["institution"], s["degree"]]
        name = tex(s["name"])
        if detail:
            name += " (%s)" % tex(", ".join(detail))
        entries.append(name)

    body = r" $\cdot$ ".join(entries)
    out += [r"\needspace{%d\baselineskip}" % (est_lines(body) + 1),
            r"\textbf{%s} (%s): \\" % (tex(heading), tex(qualifier)),
            r"\indent \hspace{1cm} \begin{minipage}[t]{0.75\textwidth}",
            body,
            r"\end{minipage}", ""]

# Honors, only if un-retired ------------------------------------------------
honors = cv.get("honors", {})
if shown(honors):
    out += [r"\section{Honors and\\ Awards}", ""]
    for group in honors["entries"]:
        out += [r"\textbf{%s:} \\" % tex(group["institution"]),
                r" $\cdot$ ".join(tex(a) for a in group["awards"]), ""]

# A \needspace *inside* a section can strand the section label: \section places
# the label in the margin, and only the content that follows gets pushed to the
# next page. So guard each section opening too, generously enough that no inner
# \needspace can fire immediately afterwards and separate label from content.
guarded = []
for line in out:
    if line.startswith(r"\section{"):
        guarded.append(r"\needspace{10\baselineskip}")
    guarded.append(line)
out = guarded

OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote %s (%d publications, %d Portuguese, %d working, %d talks)"
      % (OUT.relative_to(ROOT), len(published), len(portuguese), len(working), len(talks)))
